# Generated by Django 2.0.4 on 2019-03-21 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FaceDetandRec', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oripic',
            name='image',
            field=models.ImageField(upload_to='img'),
        ),
        migrations.AlterField(
            model_name='tarpic',
            name='image',
            field=models.ImageField(upload_to='img'),
        ),
    ]
