# Generated by Django 2.0.4 on 2019-03-24 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FaceDetandRec', '0003_auto_20190321_1502'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oripic',
            name='imageOri',
            field=models.ImageField(upload_to='imgOri'),
        ),
        migrations.AlterField(
            model_name='tarpic',
            name='imageTar',
            field=models.ImageField(upload_to='imgTar'),
        ),
    ]
